"""add user profile fields (display_name, profile_photo_url)

Revision ID: a5f4e31c2d70
Revises: a2564f477e8d
Create Date: 2026-08-10 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5f4e31c2d70'
down_revision: Union[str, None] = 'a2564f477e8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('display_name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('profile_photo_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_photo_url')
    op.drop_column('users', 'display_name')
    # ### end Alembic commands ###
